session_secret: adadasdasfasfasfasfasfasfasfasfa
timezone_offset: 0
database:
  common: &common
    adapter: mysql2
    encoding: utf8
    reconnect: true
    host: localhost
    username: root
    password: root

  development:
    <<: *common
    database: sysopia_dev

  test:
    <<: *common
    database: sysopia_test

  production:
    <<: *common
    database: sysopia
