session_secret: <%= ENV["SYSOPIA_SESSION_SECRET"] %>
timezone_offset: <%= ENV["SYSOPIA_TIMEZONE_OFFSET"] %>
database:
  common: &common
    adapter: mysql2
    encoding: utf8
    reconnect: true
    host: <%= ENV["SYSOPIA_DB_HOST"] %>
    username: <%= ENV["SYSOPIA_DB_USERNAME"] %>
    password: <%= ENV["SYSOPIA_DB_PASSWORD"] %>

  development:
    <<: *common
    database: sysopia_dev

  test:
    <<: *common
    database: sysopia_test

  production:
    <<: *common
    database: sysopia